trigger:
- none

pool:
  name: "poolcapstone"

jobs:
- job: InstallTools
  displayName: 'Install Development Tools on Rocky Linux'
  steps:

    # Checkout the repository where the pipeline YAML is located
    - checkout: self
      displayName: 'Checkout Pipeline Source Repository'

    # Git clone the repository that contains your playbook and other files
    - script: |
        git clone --branch main git@ssh.dev.azure.com:v3/saunakdevops/CS-Saunak/IS-saunak cloned-repo
      displayName: 'Git Clone Repository'

    # Run the Ansible playbook to install tools and clone the repo on the target machine
    - script: |
        ansible-playbook -i /etc/ansible/hosts ansible-playbook.yaml
      displayName: 'Run Ansible Playbook'

