# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
trigger:
  none
 
pool:
  #vmImage: ubuntu-latest
  name: "poolcapstone"
 
stages:
# Stage 1: Git Clone
- stage: GitClone
  displayName: "Clone Repository"
  jobs:
  - job: CloneJob
    displayName: "Clone Git Repository"
    steps:
    - checkout: self
      displayName: "Checkout Source Code"
 
# - stage: RunAnsiblePlaybook 
#   displayName: "Run Ansible Playbook to Install"
#   dependsOn: GitClone
#   jobs:
#   - job: InstallTerraform
#     steps:
#     - script: |
#         echo "Running Ansible playbook to install ..."
#         ansible-playbook ./ansible-playbook.yaml

# Stage 2: Run Ansible Playbook to Install Terraform
  - stage: RunAnsiblePlaybook 
    displayName: "Run Ansible Playbook to Install"
    dependsOn: GitClone
    jobs:
      - job: InstallTerraform
        displayName: "Install Terraform"
        steps:
          - script: |
              echo "Running Ansible playbook to install Terraform..."
              ansible-playbook ./install-terraform.yaml  # This is the playbook you want to run
            displayName: "Run install-terraform.yaml Playbook"